### ISSUE TITLE
Support for file update

### ISSUE THREAD

**Issue by kanakoubukata** [kintone/kintoneUtility#1]
Would you please support for file upload.

https://cybozudev.zendesk.com/hc/ja/articles/200724665

**Comment by yasu-o** [comment]
We appreciate your proposal!
By the way, For what purpose do you use the library?

**Comment by kanakoubukata** [comment]
アシアル株式会社の生形と申します。
日本語で大丈夫ということでしたので日本語で失礼します。
弊社で運営しております「Monaca」というサービスのプロダクトパートナーとしてkintoneもご登録頂いております。
kintoneとMonacaの連携機能の強化のためにSDK側でのご対応をお願いしたくご連絡しました。

Monaca
https://ja.monaca.io/

MonacaはHTMLやJavaScriptといったWebのフロントエンド技術でモバイルアプリを開発するサービスでして、
現状はkintoneと連携するにはREST APIを使うしか手段がないのですが、
外部から利用可能なSDKがありますと、1クリックでkintoneとの連携が可能となります。
また認証やファイルアップロードといった処理をREST APIで実行するとソースコードが冗長になってしまうのですが、
SDKによって簡易的に利用できるようになれば、双方のユーザー拡大の効果があると見込んでおります。

ご検討頂けますと幸いです。何卒よろしくお願い致します。

**Comment by sada-nishio** [comment]
Fixed by v.0.2.0
