### ISSUE TITLE
ステータス更新用のAPIについて

### ISSUE THREAD

**Issue by masahixixi** [kintone/kintoneUtility#12]
* https://developer.cybozu.io/hc/ja/articles/204791550

kintoneUtility で上記ステータス更新を行いたいと考えているのですが対応をお願いできますでしょうか。

**Comment by trung-doan** [comment]
@masahixixi 
Thank you for your ideas.

Currently, we have halted the expansion of functionality for kintoneUtility.
We are planning to implement the new lib named kintone-js-sdk and your needed functions will be available.
Sorry about this inconvenience.
