### ISSUE TITLE
Documenting Upsert Records Limit

### ISSUE THREAD

**Issue by theredspoon** [kintone/kintoneUtility#17]
The [code on line 9 in upsertRecords.js](https://github.com/kintone/kintoneUtility/blob/master/src/js/rest/upsertRecords.js) comments that up to 1500 records can be updated at a time. However, the [REST documentation](https://github.com/kintone/kintoneUtility/blob/master/guides/rest_doc.md#upsertRecords) does not mention this limitation. Could you please clarify? Thank you!

**Comment by ghost** [comment]
Thank you for reporting this issue. We've pushed a new [commit](https://github.com/kintone/kintoneUtility/commit/b74ab640383b48e8e01c5abb3b2eb894b596b0ad) in which the limitations are mentioned in REST documentation. In your case of upsertRecord.js, kintoneUtility will throw an error when handling over 1500 records.
