### ISSUE TITLE
【要望】ユーザー認証機能の追加

### ISSUE THREAD

**Issue by kanakoubukata** [kintone/kintoneUtility#2]
お世話になります。
以下の機能をサポートして頂き、外部サイト/アプリからもkintoneの操作ができるようにして頂けないでしょうか。
[REST APIの共通仕様#ユーザー認証](https://cybozudev.zendesk.com/hc/ja/articles/201941754#step7)

よろしくお願い致します。

**Comment by sada-nishio** [comment]
Fixed by v.0.2.0
