### ISSUE TITLE
Please publish on NPM

### ISSUE THREAD

**Issue by the-red** [kintone/kintoneUtility#20]
Hi!
Thank you for merge PR #18 

Now, I'd like to install kintoneUtility as follows.
```
yarn add kintone-utility
```
Please publish on NPM! 🙇

**Comment by trung-doan** [comment]
@TheRed 
Thank you for your suggestion.
We will consider about it.

**Comment by trung-doan** [comment]
@TheRed 
Thank you for always using our kintone Utility.
We have considered about your request, but currently we’re planning to develope a subsequent project of kintone Utility, so we decided to not publish kintone Utility to npm.
Thank for your kind understanding in advance.

**Comment by the-red** [comment]
OK. I understand it.
I expect subsequent project of kintone Utility! 😁

**Comment by trung-doan** [comment]
@TheRed 
So, i will closed this issue.
Thank you very much!
